export const Config = {
    MONGODB_URL: process.env.MONGODB_URL,
    MONGODB_PORT: process.env.MONGODB_PORT,
    MONGODB_DATABASE: process.env.MONGODB_DATABASE,
    JWT_SECRET: process.env.JWT_SECRET,
    JWT_EXPIRATION: process.env.JWT_EXPIRATION,
    MSSQL_URL: process.env.MSSQL_URL,
    MSSQL_USER: process.env.MSSQL_USER,
    MSSQL_PASS: process.env.MSSQL_PASS,
    MSSQL_PORT: process.env.MSSQL_PORT,
    MSSQL_DATABASE_YEARPM: process.env.MSSQL_DATABASE_YEARPM,
    MSSQL_DATABASE_SERVE0PM: process.env.MSSQL_DATABASE_SERVE0PM,
    MSSQL_DATABASE_GRUP0001: process.env.MSSQL_DATABASE_GRUP0001
}
